baseURL = 'https://example.org/'
languageCode = 'en-uk'
title = "Loup Menjoulet's personal website"
theme = 'lean'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1

[languages.fr]
contentDir = "content/fr"
languageName = "Français"
weight = 2
